### PR TITLE
Street Address Support / Rooftop Accuracy

### PR DESCRIPTION
**Pull request by fastdivision**
This PR is an iteration on #22 (kindly provided by @bradmkjr) and addresses issue #21, after cleaning up the codebase.

The customer's street address is passed to our API for rooftop accurate calculations. Additionally, we store the merchant's shipping origin address for the `from_street` parameter and local pickup calculations:

screen shot 2017-07-25 at 2 10 22 pm

We're still reliant on Woo's native tax tables for looking up rates by city and zip code. We don't save any street addresses in these tables. If there's a rate match in the tax table by city and zip after making a request to our API, that rate will be updated. If two customers from the same city and zip code are simultaneously checking out, the rate should immediately update on order creation to prevent any collisions or data issues. The current rate is saved directly to the order at the line item level, so if it changes again after a calculation, existing orders will not be affected.

**Ship From Address Handling in WooCommerce 3.2**

screen shot 2017-11-02 at 2 05 37 pm

**Ship From Address Handling in WooCommerce 2.6 - 3.1**

screen shot 2017-11-02 at 2 03 06 pm

**Todos:**

- [x] Intercept `woocommerce_calc_line_taxes` AJAX call to pass street address for `$_POST` for backend orders
- [x] Fix backend order calculations for Woo 2.6.x
- [x] Consider using store address street field in Woo 3.2+ or pre-populating if available

**Versions Tested:**

- [x] Woo 3.2
- [x] Woo 3.1
- [x] Woo 3.0
- [x] Woo 2.6.2
- [ ] Woo 2.6.1
- [ ] Woo 2.6.0

### CODE REVIEW

**Comment by villav** [comment]
Hi.

Does this change will merged to master soon?

Thanks

**Comment by fastdivision** [comment]
@villav Yes we're planning to merge this branch soon after we get backend calculations working with street addresses and perform some additional testing in WooCommerce 2.6.x.

**Comment by jeffstieler** [comment]
Is there a timeline for inclusion into `master`? We're getting issues logged for street address support as well: https://github.com/Automattic/woocommerce-services/issues/1355

**Comment by SiR-DanieL** [comment]
Hello! Any update on this?

**Comment by fastdivision** [comment]
@jeffstieler @SiR-DanieL This is at the top of my list, hopefully within the next month. We pushed it back to refactor the plugin for improved stability in our 1.6 release. So far so good. Most of the functionality is ready, just need to update some things around the refactor and thoroughly test in Woo 2.6 - 3.3. Thank you for your patience guys, I know many people are waiting for this!

**Comment by spraveenitpro** [comment]
Hi @fastdivision 

Just checking on this a quite a few folks are looking for an update. :)

Thanks

**Comment by fastdivision** [comment]
@spraveenitpro This functionality has been pushed back again to address open performance issues and bugs. Working on it as soon as I can!

**Comment by fastdivision** [comment]
Continuing this PR in #75, ready for testing 👍

**Pull request closed without merging**
