### PR TITLE
Street Address Support / Rooftop Accuracy

### PR DESCRIPTION
**Pull request by fastdivision**
This PR is a continuation of #33 and gives us a fresh start with improvements and bug fixes from recent versions of the TaxJar plugin.

**Versions Tested:**

- [x] Woo 3.4
- [x] Woo 3.3
- [x] Woo 3.2
- [x] Woo 3.1
- [x] Woo 3.0
- [x] Woo 2.6.2
- [x] Woo 2.6.1
- [x] Woo 2.6.0

### CODE REVIEW

**Comment by fastdivision** [comment]
When testing between versions, be mindful of **Base Location** and the ship from fields within the TaxJar plugin. After 3.2, we'll use the new location fields under the **General** tab in WooCommerce instead of TaxJar's fields. If you revert to an older version, make sure **Ship From Zip Code** falls within the state set for **Base Location** to avoid calculation errors.

**Comment by ChrisColotti** [comment]
The City Tax rate not getting calculated #1355 is affecting me and I cannot use auto calculations as it's pulling the wrong tax rate for my base location.  Is there any ETA when a fix will be rolled out?  I had to revert to manual calculations for my city but if/when the full US tax in every state goes into effect I will need to open a TaxJar account and revert back to auto.

**Comment by fastdivision** [comment]
All automated tests passing across the board 🎉

**Comment by matthewecampbell** [comment]
✅ 2.6.0 Back end calcs 
✅ 3.0.0 Back end calcs 
✅ 3.1.0 Back end calcs 
✅ 3.2.0 Back end calcs
✅ 3.3.0 Back end calcs
✅ 3.4.4 Back end calcs
✅ 3.4.4 Front end calcs
✅ 3.3.1 Front end calls
✅ 3.2.1 Front end calcs
✅ 3.1.1 Front end calcs
✅ 3.0.1 Front end calcs
✅ 2.6.1 Front end calcs

**Pull request merged**
